version: "3.3"
services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: udcbot
      POSTGRES_USER: udcbot
      POSTGRES_PASSWORD: 123456789

  adminer:
    image: adminer:4
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula

  bot:
    build: .
    volumes:
      - .\DiscordBot\Settings\:/app/Settings
      - .\DiscordBot\SERVER\:/app/SERVER
      - .\DiscordBot\Assets\:/app/Assets:ro
    depends_on:
      - db
    restart: always

volumes:
  db_data:
