version: "3.3"
services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: udcbot
      POSTGRES_USER: udcbot
      POSTGRES_PASSWORD: 123456789

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpass:/pgpass_src:ro
    entrypoint: >
      /bin/sh -c "
      cp /pgpass_src /tmp/pgpass &&
      chmod 600 /tmp/pgpass &&
      /entrypoint.sh
      "

  bot:
    build: .
    volumes:
      - .\DiscordBot\Settings\:/app/Settings
      - .\DiscordBot\SERVER\:/app/SERVER
      - .\DiscordBot\Assets\:/app/Assets:ro
    depends_on:
      - db
    restart: always

volumes:
  db_data:
