services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: udcbot
      POSTGRES_USER: udcbot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456789}

  adminer:
    image: adminer:4
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula

  bot:
    build: .
    environment:
      UDCBOT_DiscordConnection__Token: ${UDCBOT_DiscordConnection__Token:-}
      UDCBOT_Database__ConnectionString: Host=db;Port=5432;Database=udcbot;Username=udcbot;Password=${POSTGRES_PASSWORD:-123456789}
      UDCBOT_Weather__ApiKey: ${UDCBOT_Weather__ApiKey:-}
      UDCBOT_Airport__FlightApiKey: ${UDCBOT_Airport__FlightApiKey:-}
      UDCBOT_Airport__FlightApiSecret: ${UDCBOT_Airport__FlightApiSecret:-}
      UDCBOT_Airport__AirLabsApiKey: ${UDCBOT_Airport__AirLabsApiKey:-}
    volumes:
      - ./DiscordBot/Settings:/app/Settings
      - ./DiscordBot/SERVER:/app/SERVER
      - ./DiscordBot/Assets:/app/Assets:ro
    depends_on:
      - db
    restart: always

volumes:
  db_data:
