services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: udcbot
      MYSQL_USER: udcbot
      MYSQL_PASSWORD: 123456789

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  bot:
    build: .
    volumes:
      - .\DiscordBot\Settings\:/app/Settings
      - .\DiscordBot\SERVER\:/app/SERVER
    depends_on:
      - db
    restart: always

volumes:
  db_data:
