name: Add Deployment Comment to PR
"on":
  pull_request_target:
    types: [opened]

jobs:
  add_deploy_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add deployment comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### 🚀 Deploy this PR to an environment

            You can deploy this PR to either development or staging environment:

            - Comment `/deploy_dev` to deploy to the **development** environment

            Alternatively, you can:
            1. Go to Actions tab
            2. Click on "Manual Deploy to Firebase" workflow
            3. Click the "Run workflow" button
            4. Select branch: `${{ github.event.pull_request.head.ref }}`
            5. Choose environment: DEV
            6. Enter a deployment message
            7. Click "Run workflow"
