name: Deploy to Test Server

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ github.workspace }}/DiscordBot/bin/Release/netcoreapp3.1/

  upload:
    name: Upload to Server
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Copy build to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ github.workspace }}/dist
          remote: ${{ secrets.SERVER_BUILD_DIR }}
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

  restart:
    name: Restart Bot
    needs: upload
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Run commands in SSH
        uses: appleboy/ssh-action@master
        with:
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            chmod +x ${{ secrets.SERVER_BUILD_DIR }}DiscordBot
            ${{ secrets.SERVER_COMMAND }}
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: Bot has been deployment to Test Server successfully.
